# https://stackoverflow.com/questions/67498836/docker-chown-changing-ownership-of-data-db-operation-not-permitted

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=BookStore
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./__docker_compose/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  dotnet-app:
    build: .
    environment:
      - OTLP_HOSTNAME=otelcol
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./__docker_compose/mimir/mimir.yaml:/etc/mimir.yaml
      - ./__docker_compose/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=otelcol:4317
      - GF_TRACING_OPENTELEMETRY_OTLP_PROPAGATION=w3c
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    volumes:
      - ./__docker_compose/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./__docker_compose/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol
    # restart: unless-stopped
    ports:
      - "14268:14268"  # jaeger ingest
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      # - /var/run/docker.sock.raw:/var/run/docker.sock
      - ./__docker_compose/otelcol/config.yaml:/etc/otelcol/config.yaml

volumes:
  mongodb-data:
